version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      args:
        - NODE_ENV=development
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/desafiojs
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - desafio-network
    command: npm run dev

  backend-test:
    build:
      context: ./backend
      args:
        - NODE_ENV=test
    container_name: backend-test
    environment:
      - NODE_ENV=test
      - MONGODB_URI=mongodb://mongodb:27017/desafiojs-test
    depends_on:
      - mongodb
    networks:
      - desafio-network
    command: sh -c "npx jest --forceExit --detectOpenHandles"

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=desafiojs
    volumes:
      - mongodb_data:/data/db
      - ./backend/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - desafio-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - desafio-network
    depends_on:
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=12345
    depends_on:
      - mongodb
    networks:
      - desafio-network

volumes:
  mongodb_data:

networks:
  desafio-network:
    driver: bridge